### ISSUE TITLE
Window Title

### ISSUE THREAD

**Issue by JamesPeters98** [sh0nk/matplotlib4j#10]
Is there any way to set the title of the window for the Figure?

I currently am opening multiple plots in different threads and would like to name each window instead of it just being 'Figure_1' for all of them!

**Comment by sh0nk** [comment]
Added `.figure(windowTitle)` call by #11 . Pull `master` branch to try it quickly! And please make sure that figure must be called before adding a new plot contents.

<img width="685" alt="Screen Shot 2020-01-03 at 0 55 24" src="https://user-images.githubusercontent.com/6478810/71676805-7e0f6700-2dc4-11ea-909a-c5c3b537fc5a.png">

**Comment by sh0nk** [comment]
Let me close this issue since it is inactive after the fix.

**Comment by JamesPeters98** [comment]
Lovely, just got to try this after the Christmas break! Works perfectly!

**Comment by sh0nk** [comment]
@JamesPeters98 Cool. Thank you for your feedback and verification!
