### ISSUE TITLE
There is no release 0.6

### ISSUE THREAD

**Issue by ennioVisco** [sh0nk/matplotlib4j#27]
The documentation says "from release 0.6.0" but there is not even a beta/alpha one.

**Comment by sh0nk** [comment]
@ennioVisco Thank you for your comment. As you mention, 0.6.0 is not released yet. As the limitation of Github, README is shown from `master` branch which includes unreleased features.

In a meanwhile, could you use `0.5.1-SNAPSHOT` including the changes? For maven, you can write `pom.xml` as:

```
<dependencies>
  <dependency>
    <groupId>com.github.sh0nk</groupId>
    <artifactId>matplotlib4j</artifactId>
    <version>0.5.1-SNAPSHOT</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>oss.sonatype.org-snapshot</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by ennioVisco** [comment]
Thanks for the quick comment, that's very useful, I'm using gradle though, I'm looking into how to do the same in gradle.

Thanks again :)

**Comment by ennioVisco** [comment]
However @sh0nk I cannot see the 0.5.1 here https://search.maven.org/artifact/com.github.sh0nk/matplotlib4j

**Comment by sh0nk** [comment]
@ennioVisco The repository URL is different between release and snapshots. [Here](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/sh0nk/matplotlib4j/0.5.1-SNAPSHOT/matplotlib4j-0.5.1-20210502.172842-1.pom) you can find the pom file.

For Gradle, this would work. Could you give it a try?

```
repositories {
    maven {url 'https://oss.sonatype.org/content/repositories/snapshots/'}
}

dependencies {
    compile "com.github.sh0nk:matplotlib4j:0.5.1-SNAPSHOT"
}
```

**Comment by ennioVisco** [comment]
> @ennioVisco The repository URL is different between release and snapshots. [Here](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/sh0nk/matplotlib4j/0.5.1-SNAPSHOT/matplotlib4j-0.5.1-20210502.172842-1.pom) you can find the pom file.
> 
> For Gradle, this would work. Could you give it a try?
> 
> ```
> repositories {
>     maven {url 'https://oss.sonatype.org/content/repositories/snapshots/'}
> }
> 
> dependencies {
>     compile "com.github.sh0nk:matplotlib4j:0.5.1-SNAPSHOT"
> }
> ```

It works, thanks a lot <3. 
Should I close the issue? Or do you want to keep it on as a reference until the publishing of 0.6.0?

**Comment by sh0nk** [comment]
Great! Let me close it. We can point to this doc if there's a person who has the same problem.
