### ISSUE TITLE
how to save the png? Plot is not support save?

### ISSUE THREAD

**Issue by CYsuncheng** [sh0nk/matplotlib4j#3]

**Comment by CYsuncheng** [comment]
is the savefig of Python is supported？

**Comment by sh0nk** [comment]
It is not yet supported on 0.2.0. However, savefig support is at the top of my backlog. It's pretty soon supported, please stay tuned until then.

**Comment by CYsuncheng** [comment]
ok，thanks a lot

**Comment by sh0nk** [comment]
Finally the latest version [0.3.0](https://github.com/sh0nk/matplotlib4j/releases/tag/0.3.0) has been released with Savefig support. Thank you for your patient and looking forward to your any feedback again.
